
# Library -----------------------------------------------------------------

library(bbr)
library(tidyverse)
library(here)

# `bbi` configuration -----------------------------------------------------

# To check if you have bbi installed and configured, run `bbi_version()`
bbi_version()
# If this doesn't return a version number, see 
# https://metrumresearchgroup.github.io/bbr/articles/getting-started.html#installing-bbi
# for installation details.

# Define model dir and load tags
# NONMEM model directory
  MODEL_DIR <- here("wk6/nm-model") 
# NONMEM installation directory at MSI
  # NONMEM_DIR <- "/common/software/install/migrated/nonmem" # Mesabi referencing NONMEM path
  NONMEM_DIR <- "/common/software/install/manual/nonmem" # Agate referencing NONMEM path
  # NONMEM_DIR <- Sys.getenv("NM_ROOT") # not useful, system path hasn't set yet 
# NONMEM version
  NONMEM_VERSION <- "750" 
# MPI installation directory at MSI
  # MPI_PATH <- "/common/software/install/migrated.intel/x86_64/2018/impi_msi/compilers_and_libraries_2018.0.128/linux/mpi/intel64/bin/mpiexec" # Mesabi referencing MPI path
  MPI_PATH <- "/common/software/install/migrated/oneapi/2022.1/mpi/2021.5.1/bin/mpiexec" # Agate referencing MPI path
  # MPI_PATH <- Sys.getenv("NM_MPIEXEC") # not useful, system path hasn't set yet

bbi_init(.dir = MODEL_DIR,
         .nonmem_dir = NONMEM_DIR, 
         .nonmem_version = NONMEM_VERSION, 
         .bbi_args = list("mpi_exec_path" = MPI_PATH))

# Submit `NONMEM` runs ----------------------------------------------------

########################################
############ Method #1 #################
########################################

# Navigate to `MODEL_DIR` in terminal
# Submit model via bash script `nm_run.sh`
# 
# Command: 
# `cd model`
# `sbatch nm_job.sh 106`
# 
# Use `squeue --me` in terminal to check run status

########################################
############ Method #2 #################
########################################

# Submit model using `submit_nonmem_model` function 
# adapted from `A2-AI/slurmtools` by Mutaz Jaber

# set path for `bbi` configuration file
options("bbi_config_path" = normalizePath("wk6/nm-model/bbi.yaml"))

# set slurm template to create bash script
options("slurm_job_template_path" = normalizePath("wk6/slurm-template.txt"))

# set a folder to contain all .out file generated by slurm
options("submission_root" = normalizePath("wk6/sub"))

# Read `NONMEM` model using `bbr`
runno <- "hwwk6"
mod <- new_model(.path = file.path(MODEL_DIR, runno), .overwrite=TRUE)

# Load `submit_nonmem_model` function
source(here("wk6/function-model.R"))

PARTITION = "msismall"     # partition at MSI see "https://www.msi.umn.edu/partitions"
NCPU = 4                   # ncpu-per-task
EMAIL = "cheng423@umn.edu" # email to receive slurm notification

submit_nonmem_model(.mod = mod, 
                    partition = PARTITION, 
                    ncpu = NCPU, 
                    email = EMAIL)

system("squeue --me")

# Use `squeue --me` in terminal to check run status

# Check model output ------------------------------------------------------

mod <- read_model(.path = file.path(MODEL_DIR, runno))
mod %>% model_summary()
